name: Build libssc DEB (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write

    env:
      PKGNAME: libssc
      PKGVERSION: 1.6.1
      PKGREL: 2

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev debhelper dh-make fakeroot devscripts git

      - name: Clone source repository
        run: |
          git clone https://github.com/alghiffaryfa19/libssc-pcm-pro.git source

      - name: Prepare DEB structure
        run: |
          cp -r source/libssc libssc
          cd libssc
          mkdir -p DEBIAN

          cat > DEBIAN/control <<EOF
          Package: lib${{ env.PKGNAME }}
          Version: ${{ env.PKGVERSION }}-${{ env.PKGREL }}
          Section: libs
          Priority: optional
          Architecture: arm64
          Maintainer: Alghiffary <alghiffaryfa19@gmail.com>
          Description: Sony Creative Software libraries
          Library for working with Sony Creative Software formats.
          EOF

      - name: Build DEB
        run: |
          cd libssc
          dpkg-deb --build . libssc_${{ env.PKGVERSION }}-${{ env.PKGREL }}_arm64.deb
          ls -la libssc_${{ env.PKGVERSION }}-${{ env.PKGREL }}_arm64.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libssc
          path: libssc_${{ env.PKGVERSION }}-${{ env.PKGREL }}_arm64.deb

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: libssc
          name: "libssc"
          draft: false
          prerelease: false
          files: libssc_${{ env.PKGVERSION }}-${{ env.PKGREL }}_arm64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
