name: Build sheng-sensors DEB (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write

    env:
      PKGNAME: sheng-sensors
      PKGVERSION: 20240917
      PKGREL: 1
      COMMIT: 199754bb37ae6d4706bd8d4b23e9e6fec2d959cc

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y wget dpkg-dev

      - name: Download source tarball
        run: |
          wget -O source.tar.gz \
            https://github.com/alghiffaryfa19/sheng-sensors-file/archive/${COMMIT}.tar.gz
          tar -xf source.tar.gz

      - name: Prepare DEB structure
        run: |
          mkdir -p deb/DEBIAN
          mkdir -p deb/

          cp -a sheng-sensors-file-${COMMIT}/. deb/

          cat > deb/DEBIAN/control <<EOF
          Package: ${PKGNAME}
          Version: ${PKGVERSION}-${PKGREL}
          Section: misc
          Priority: optional
          Architecture: arm64
          Maintainer: Fauzan Amir Al Ghiffary <alghiffaryfa19@gmail.com>
          Description: Sensor files for Xiaomi Mi Pad 6s Pro
           Proprietary sensor configuration files.
          EOF

      - name: Fix permissions
        run: |
          find deb -type d -exec chmod 755 {} \;
          find deb -type f -exec chmod 644 {} \;

      - name: Build DEB package
        run: |
          dpkg-deb --build deb
          mv deb.deb sheng-sensors.deb
          ls -la sheng-sensors.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sheng-sensors
          path: sheng-sensors.deb

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: sensors
          name: "sensors"
          draft: false
          prerelease: false
          files: sheng-sensors.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
